package com.quiz.security;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Base64;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link PasswordUtil}.
 *
 * <p>The expected hashes below were <b>not</b> produced by this class. They come from
 * an independent implementation (Python's {@code hashlib.pbkdf2_hmac} with SHA-256 and
 * a 32-byte derived key), so these tests would catch a mistake in the Java encoding:
 * a wrong character set for the password, a non-standard Base64 alphabet, a different
 * derived-key length or a different stored layout.
 */
class PasswordUtilTest {

    /** 16 fixed salts, Base64 encoded, so the vectors are reproducible. */
    private static final String SALT_A = "AAECAwQFBgcICQoLDA0ODw==";
    private static final String SALT_B = "EBESExQVFhcYGRobHB0eHw==";
    private static final String SALT_C = "Dx4tPEtaaXiHlqW0w9Lh8A==";

    /** "teacher123" with SALT_A at 210,000 iterations. */
    private static final String V_TEACHER =
            "PBKDF2:210000:AAECAwQFBgcICQoLDA0ODw==:+WRaa9Yu9g8N/ZMdLu2CHwpmSSKH7ErY4Ti4IQkz84M=";

    /** "student123" with SALT_B at 210,000 iterations. */
    private static final String V_STUDENT =
            "PBKDF2:210000:EBESExQVFhcYGRobHB0eHw==:xmlfVVbH3zxLNMnd3Dt3fKgCt7tUab4jgMkPZlzVvuE=";

    /** "correct horse battery staple" with SALT_C at 210,000 iterations. */
    private static final String V_PASSPHRASE =
            "PBKDF2:210000:Dx4tPEtaaXiHlqW0w9Lh8A==:K+spoPtGSalt9e+OZSMwAQGoma3ygnAZUzEjg94anm8=";

    /** "teacher123" with SALT_A at only 1,000 iterations. */
    private static final String V_WEAK_ITERATIONS =
            "PBKDF2:1000:AAECAwQFBgcICQoLDA0ODw==:UCDjmg92FayVckPTr9FmJnY43ihel6qY+tyHv66wOng=";

    /** The Urdu password "پاس ورڈ123" with SALT_B; proves UTF-8 encoding of the password. */
    private static final String URDU_PASSWORD = "\u067E\u0627\u0633 \u0648\u0631\u0688" + "123";
    private static final String V_URDU =
            "PBKDF2:210000:EBESExQVFhcYGRobHB0eHw==:1ihdrhVIZNjJaGeTmOrmIuiRbSi3nTvwxu37q0Culvo=";

    private static byte[] decode(String base64) {
        return Base64.getDecoder().decode(base64);
    }

    // ------------------------------------------------------------------
    // Agreement with the independent implementation
    // ------------------------------------------------------------------

    @Test
    @DisplayName("encode() reproduces hashes generated by an independent implementation")
    void encodeMatchesExternalVectors() {
        assertEquals(V_TEACHER, PasswordUtil.encode("teacher123", decode(SALT_A), 210_000));
        assertEquals(V_STUDENT, PasswordUtil.encode("student123", decode(SALT_B), 210_000));
        assertEquals(V_PASSPHRASE,
                PasswordUtil.encode("correct horse battery staple", decode(SALT_C), 210_000));
        assertEquals(V_URDU, PasswordUtil.encode(URDU_PASSWORD, decode(SALT_B), 210_000));
    }

    @Test
    @DisplayName("encode() honours the iteration count it is given")
    void encodeUsesSuppliedIterationCount() {
        assertEquals(V_WEAK_ITERATIONS, PasswordUtil.encode("teacher123", decode(SALT_A), 1_000));
        assertNotEquals(V_TEACHER, V_WEAK_ITERATIONS,
                "the same password and salt must yield different hashes at different costs");
    }

    // ------------------------------------------------------------------
    // verify()
    // ------------------------------------------------------------------

    @Test
    @DisplayName("verify() accepts the correct password for every stored vector")
    void verifyAcceptsCorrectPassword() {
        assertTrue(PasswordUtil.verify("teacher123", V_TEACHER));
        assertTrue(PasswordUtil.verify("student123", V_STUDENT));
        assertTrue(PasswordUtil.verify("correct horse battery staple", V_PASSPHRASE));
        assertTrue(PasswordUtil.verify("teacher123", V_WEAK_ITERATIONS));
        assertTrue(PasswordUtil.verify(URDU_PASSWORD, V_URDU));
    }

    @Test
    @DisplayName("verify() rejects an incorrect password")
    void verifyRejectsWrongPassword() {
        assertFalse(PasswordUtil.verify("teacher124", V_TEACHER));
        assertFalse(PasswordUtil.verify("", V_TEACHER));
        assertFalse(PasswordUtil.verify("TEACHER123", V_TEACHER), "passwords are case sensitive");
        assertFalse(PasswordUtil.verify("student123", V_TEACHER), "a different user's password must not match");
        assertFalse(PasswordUtil.verify(" teacher123", V_TEACHER), "surrounding whitespace is not trimmed");
    }

    @Test
    @DisplayName("verify() rejects null arguments instead of throwing")
    void verifyRejectsNulls() {
        assertFalse(PasswordUtil.verify(null, V_TEACHER));
        assertFalse(PasswordUtil.verify("teacher123", null));
        assertFalse(PasswordUtil.verify(null, null));
    }

    @Test
    @DisplayName("verify() still accepts legacy plain-text passwords")
    void verifyAcceptsLegacyPlainText() {
        // Rows written before hashing was introduced hold the raw password.
        assertTrue(PasswordUtil.verify("oldplainpw", "oldplainpw"));
        assertFalse(PasswordUtil.verify("wrong", "oldplainpw"));
        assertFalse(PasswordUtil.verify("oldplainpw", "OLDPLAINPW"));
    }

    @Test
    @DisplayName("a malformed hash falls back to a literal comparison rather than throwing")
    void verifyTreatsMalformedHashAsLegacyText() {
        String malformed = "PBKDF2:not-a-number:xxx:yyy";
        assertTrue(PasswordUtil.verify(malformed, malformed));
        assertFalse(PasswordUtil.verify("anything", malformed));

        String badBase64 = "PBKDF2:210000:!!!!:zzzz";
        assertTrue(PasswordUtil.verify(badBase64, badBase64));
        assertFalse(PasswordUtil.verify("teacher123", badBase64));

        assertFalse(PasswordUtil.verify("teacher123", "PBKDF2:210000:onlyThreeParts"));
    }

    // ------------------------------------------------------------------
    // needsRehash()
    // ------------------------------------------------------------------

    @Test
    @DisplayName("needsRehash() flags legacy and weak values, and accepts current ones")
    void needsRehashDetectsUpgradeableRows() {
        assertTrue(PasswordUtil.needsRehash("oldplainpw"), "legacy plain text must be upgraded");
        assertTrue(PasswordUtil.needsRehash(V_WEAK_ITERATIONS), "a low iteration count must be upgraded");
        assertTrue(PasswordUtil.needsRehash(null), "a missing value cannot be trusted");
        assertTrue(PasswordUtil.needsRehash("PBKDF2:not-a-number:xxx:yyy"));

        assertFalse(PasswordUtil.needsRehash(V_TEACHER));
        assertFalse(PasswordUtil.needsRehash(V_STUDENT));
        assertFalse(PasswordUtil.needsRehash(V_URDU));
    }

    // ------------------------------------------------------------------
    // hash()
    // ------------------------------------------------------------------

    @Test
    @DisplayName("hash() output verifies, is salted, and uses the current iteration count")
    void hashProducesVerifiableSaltedOutput() {
        String first = PasswordUtil.hash("teacher123");
        String second = PasswordUtil.hash("teacher123");

        assertTrue(PasswordUtil.verify("teacher123", first));
        assertTrue(PasswordUtil.verify("teacher123", second));
        assertFalse(PasswordUtil.verify("teacher124", first));

        assertNotEquals(first, second, "a random salt must make two hashes of the same password differ");
        assertTrue(first.startsWith("PBKDF2:" + PasswordUtil.ITERATIONS + ":"),
                "the stored value must record its own cost factor");
        assertFalse(PasswordUtil.needsRehash(first), "a freshly created hash must not need upgrading");
        assertFalse(first.contains("teacher123"), "the plain password must not appear in the stored value");
    }

    @Test
    @DisplayName("hash() rejects a null or empty password")
    void hashRejectsBlankPassword() {
        assertThrows(IllegalArgumentException.class, () -> PasswordUtil.hash(null));
        assertThrows(IllegalArgumentException.class, () -> PasswordUtil.hash(""));
    }

    @Test
    @DisplayName("hash() output fits in the VARCHAR(255) password column")
    void hashFitsDatabaseColumn() {
        // 4 + 1 + len(iterations) + 1 + 24 (16-byte salt) + 1 + 44 (32-byte key)
        String hash = PasswordUtil.hash("a-long-password-value-for-measurement");
        assertTrue(hash.length() <= 255,
                "hash length " + hash.length() + " would overflow users.password");
    }
}
